from __future__ import annotations
"""D 模块 A 负责人使用的枚举常量。"""

SOURCE_TYPE_DOCX = "docx"
SOURCE_TYPE_PDF = "pdf"
SOURCE_TYPE_IMAGE = "image"

SOURCE_TYPES = {SOURCE_TYPE_DOCX, SOURCE_TYPE_PDF, SOURCE_TYPE_IMAGE}

# 当前策略：
# - DOCX：混合处理，文本直接提取，内嵌图片按出现位置做标记并 OCR。
# - PDF：文本层优先；无可用文本的页面按页渲染后 OCR。
# - JPG/PNG：作为单页图片 OCR。
PARSE_MODE_DOCX_MIXED = "docx_mixed"
PARSE_MODE_PDF_IMAGE = "pdf_image"
PARSE_MODE_IMAGE = "image"

# 兼容旧版本字段，避免历史 JSON / 测试样本无法校验。
PARSE_MODE_DOCX = "docx"
PARSE_MODE_DOCX_IMAGE = "docx_image"
PARSE_MODE_PDF_TEXT = "pdf_text"
PARSE_MODE_PDF_SCAN = "pdf_scan"

PARSE_MODES = {
    PARSE_MODE_DOCX_MIXED,
    PARSE_MODE_PDF_IMAGE,
    PARSE_MODE_IMAGE,
    PARSE_MODE_DOCX,
    PARSE_MODE_DOCX_IMAGE,
    PARSE_MODE_PDF_TEXT,
    PARSE_MODE_PDF_SCAN,
}

TASK_STATUS_UPLOADED = "uploaded"
TASK_STATUS_CLASSIFIED = "classified"
TASK_STATUS_PARSED = "parsed"
TASK_STATUS_RENDERED = "rendered"
TASK_STATUS_PREPROCESSED = "preprocessed"
TASK_STATUS_OCR_DONE = "ocr_done"
TASK_STATUS_FAILED = "failed"

TASK_STATUSES = {
    TASK_STATUS_UPLOADED,
    TASK_STATUS_CLASSIFIED,
    TASK_STATUS_PARSED,
    TASK_STATUS_RENDERED,
    TASK_STATUS_PREPROCESSED,
    TASK_STATUS_OCR_DONE,
    TASK_STATUS_FAILED,
}

COORDINATE_BASE_PREPROCESSED_IMAGE = "preprocessed_image"
COORDINATE_BASE_PAGE_IMAGE = "page_image"

BBOX_SOURCE_OCR = "ocr"
BBOX_SOURCE_ESTIMATED = "estimated"
BBOX_SOURCE_RENDERED = "rendered"
BBOX_SOURCES = {BBOX_SOURCE_OCR, BBOX_SOURCE_ESTIMATED, BBOX_SOURCE_RENDERED}

SOURCE_MODE_OCR = "ocr"
SOURCE_MODE_TEXT_EXTRACT = "text_extract"
SOURCE_MODE_IMAGE_MARKER = "image_marker"
SOURCE_MODES = {SOURCE_MODE_OCR, SOURCE_MODE_TEXT_EXTRACT, SOURCE_MODE_IMAGE_MARKER}

BLOCK_TYPE_TEXT = "text"
BLOCK_TYPE_IMAGE_MARKER = "image_marker"
BLOCK_TYPE_IMAGE_OCR = "image_ocr"
BLOCK_TYPES = {BLOCK_TYPE_TEXT, BLOCK_TYPE_IMAGE_MARKER, BLOCK_TYPE_IMAGE_OCR}

STAGE_FILE_INGEST = "file_ingest"
STAGE_DOCUMENT_PARSER = "document_parser"
STAGE_PAGE_RENDERER = "page_renderer"
STAGE_IMAGE_PREPROCESS = "image_preprocess"
STAGE_OCR_ENGINE = "ocr_engine"

STAGES = {
    STAGE_FILE_INGEST,
    STAGE_DOCUMENT_PARSER,
    STAGE_PAGE_RENDERER,
    STAGE_IMAGE_PREPROCESS,
    STAGE_OCR_ENGINE,
}
